name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Surge
      run: |
        # Configurar Surge.sh
        npm install --global surge
        surge token a11a02edb123b72b0c7c316c18e27d1b 

        # Desplegar en Surge.sh
        surge ./ --domain deranged-bucket.surge.sh --token ${{ secrets.SURGE_TOKEN }}
